# Generated by Django 5.0.2 on 2024-02-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('banner_created_at', models.DateTimeField(auto_created=True)),
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_image', models.ImageField(null=True, upload_to='images/')),
                ('banner_status', models.CharField(default='Active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_create_at', models.DateTimeField(auto_created=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_material', models.CharField(max_length=100)),
                ('product_color', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_status', models.CharField(default='Active', max_length=100)),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=100)),
                ('video_description', models.TextField()),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='UserEnquiryModel',
            fields=[
                ('enquiry_create_at', models.DateTimeField(auto_created=True)),
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry_user', models.CharField(max_length=200)),
                ('enquiry_phone', models.CharField(max_length=100)),
                ('enquiry_subject', models.CharField(max_length=300)),
                ('enquiry_message', models.TextField()),
                ('enquiry_status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'enquiry_table',
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(null=True, upload_to='images/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirWellApp.productmodel')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
    ]
