# Generated by Django 5.0.2 on 2024-02-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirWellApp', '0002_productcategorymodel_productmodel_product_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategorymodel',
            table='category_table',
        ),
    ]
