# Generated by Django 5.0.2 on 2024-02-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirWellApp', '0003_alter_productcategorymodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenquirymodel',
            name='enquiry_create_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
