# Generated by Django 5.0.2 on 2024-02-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirWellApp', '0005_alter_productmodel_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='banner_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userenquirymodel',
            name='enquiry_create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
