# Generated by Django 5.0.2 on 2024-02-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirWellApp', '0006_alter_bannermodel_banner_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicevideo',
            name='video_description',
        ),
        migrations.RemoveField(
            model_name='servicevideo',
            name='video_name',
        ),
    ]
