# Generated by Django 5.0.2 on 2024-03-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirWellApp', '0007_remove_servicevideo_video_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
